In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

import os
import sys
os.chdir("..")

df_listings = pd.read_csv('data/combined_csvs/listings_property_vals.csv')
df_future = pd.read_csv('data/combined_csvs/future_rates.csv')
df_past = pd.read_csv('data/combined_csvs/past_rates.csv')
df_reviews = pd.read_csv('data/combined_csvs/reviews.csv')

In [14]:
len(df_listings)

2882

In [2]:
df_listings.columns

Index(['listing_id', 'listing_name', 'description', 'listing_type',
       'room_type', 'cover_photo_url', 'photos_count', 'photo_urls', 'host_id',
       'host_name', 'cohost_ids', 'cohost_names', 'superhost', 'latitude',
       'longitude', 'guests', 'bedrooms', 'beds', 'baths', 'registration',
       'amenities', 'instant_book', 'professional_management', 'min_nights',
       'cancellation_policy', 'checkin_time', 'checkout_time',
       'guest_favorite', 'exact_location', 'currency', 'cleaning_fee',
       'extra_guest_fee', 'single_fee_structure', 'num_reviews',
       'rating_overall', 'rating_accuracy', 'rating_checkin',
       'rating_cleanliness', 'rating_communication', 'rating_location',
       'rating_value', 'ttm_revenue', 'ttm_revenue_native', 'ttm_avg_rate',
       'ttm_avg_rate_native', 'ttm_occupancy', 'ttm_adjusted_occupancy',
       'ttm_revpar', 'ttm_revpar_native', 'ttm_adjusted_revpar',
       'ttm_adjusted_revpar_native', 'ttm_avg_min_nights',
       'ttm_avg_length_of_stay', 'ttm_reserved_days', 'ttm_blocked_days',
       'ttm_available_days', 'ttm_total_days', 'l90d_revenue',
       'l90d_revenue_native', 'l90d_avg_rate', 'l90d_avg_rate_native',
       'l90d_occupancy', 'l90d_adjusted_occupancy', 'l90d_revpar',
       'l90d_revpar_native', 'l90d_adjusted_revpar',
       'l90d_adjusted_revpar_native', 'l90d_avg_min_nights',
       'l90d_avg_length_of_stay', 'l90d_reserved_days', 'l90d_blocked_days',
       'l90d_available_days', 'l90d_total_days', 'city'],
      dtype='str')

In [3]:
df_future.columns

Index(['listing_id', 'date', 'vacant_days', 'reserved_days', 'occupancy',
       'revenue', 'rate_avg', 'booked_rate_avg', 'booking_lead_time_avg',
       'length_of_stay_avg', 'min_nights_avg', 'native_booked_rate_avg',
       'native_rate_avg', 'native_revenue', 'city'],
      dtype='str')

In [16]:
df_past

,listing_id,date,vacant_days,reserved_days,occupancy,revenue,rate_avg,booked_rate_avg,booking_lead_time_avg,length_of_stay_avg,min_nights_avg,native_booked_rate_avg,native_rate_avg,native_revenue,city
0,19316556,2025-06-01,7,23,0.767,4806.0,205.8,209.0,7.0,2.0,2.0,209.0,206.0,4806.0,gatlinburg
1,19316556,2025-07-01,3,28,0.903,5660.0,201.1,202.1,10.0,3.0,2.0,202.0,201.0,5660.0,gatlinburg
2,19316556,2025-08-01,7,24,0.774,3878.0,159.3,161.6,8.0,2.0,2.0,162.0,159.0,3878.0,gatlinburg
3,19316556,2025-09-01,11,19,0.633,2550.0,138.2,134.2,24.0,3.0,2.0,134.0,138.0,2550.0,gatlinburg
4,19316556,2025-10-01,7,24,0.774,4708.0,193.9,196.2,29.0,3.0,2.0,196.0,194.0,4708.0,gatlinburg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34100,30496620,2026-01-01,16,15,0.484,2495.0,166.1,166.3,25.0,3.0,2.0,166.0,166.0,2495.0,durham
34101,30496620,2026-02-01,15,13,0.464,2156.0,165.9,165.8,9.0,2.0,2.0,166.0,166.0,2156.0,durham
34102,30496620,2026-03-01,14,17,0.548,3301.0,187.7,194.2,21.0,3.0,2.0,194.0,188.0,3301.0,durham
34103,30496620,2026-04-01,14,16,0.533,3132.0,190.8,195.8,89.0,1.0,2.0,196.0,191.0,3132.0,durham
34104,30496620,2026-05-01,6,25,0.806,5917.0,231.6,236.7,58.0,3.0,2.0,237.0,232.0,5917.0,durham

In [15]:
df_future

,listing_id,date,vacant_days,reserved_days,occupancy,revenue,rate_avg,booked_rate_avg,booking_lead_time_avg,length_of_stay_avg,min_nights_avg,native_booked_rate_avg,native_rate_avg,native_revenue,city
0,21151625,2026-06-01,3,27,0.900,12693.0,477.0,470.1,65.0,5.0,2.0,470.0,477.0,12693.0,myrtle beach
1,21151625,2026-07-01,9,22,0.710,10556.0,494.0,479.8,106.0,6.0,2.0,480.0,494.0,10556.0,myrtle beach
2,21151625,2026-08-01,24,7,0.226,2422.0,399.2,346.0,151.0,7.0,2.0,346.0,399.0,2422.0,myrtle beach
3,21151625,2026-09-01,30,0,0.000,0.0,288.9,NaN,NaN,NaN,3.0,NaN,289.0,0.0,myrtle beach
4,21151625,2026-10-01,31,0,0.000,0.0,273.7,NaN,NaN,NaN,3.0,NaN,274.0,0.0,myrtle beach
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33487,47923982,2027-01-01,31,0,0.000,0.0,129.5,NaN,NaN,NaN,2.0,NaN,130.0,0.0,durham
33488,47923982,2027-02-01,28,0,0.000,0.0,127.8,NaN,NaN,NaN,2.0,NaN,128.0,0.0,durham
33489,47923982,2027-03-01,31,0,0.000,0.0,127.7,NaN,NaN,NaN,2.0,NaN,128.0,0.0,durham
33490,47923982,2027-04-01,30,0,0.000,0.0,128.3,NaN,NaN,NaN,2.0,NaN,128.0,0.0,durham
33491,47923982,2027-05-01,31,0,0.000,0.0,128.0,NaN,NaN,NaN,2.0,NaN,128.0,0.0,durham

In [4]:
df_reviews.head()

,listing_id,date,num_reviews,reviewers,city
0,33573182,2025-08-01,2,"555114068,103251391",raleigh
1,33573182,2026-03-01,1,679230494,raleigh
2,33576344,2025-09-01,2,"234588281,199555687",raleigh
3,33576344,2025-11-01,1,440551493,raleigh
4,33576344,2026-03-01,4,"53439008,224744609,534686213,393737201",raleigh

In [5]:
df_listings.room_type.value_counts()

room_type
entire_home     2545
private_room     325
hotel_room         9
shared_room        3
Name: count, dtype: int64

In [6]:
df_listings.superhost.value_counts()

superhost
True     1719
False    1163
Name: count, dtype: int64

In [7]:
df_listings.guest_favorite.value_counts()

guest_favorite
True     1341
False     899
Name: count, dtype: int64

In [8]:
df_listings.cancellation_policy.value_counts()

cancellation_policy
Firm                    1002
Moderate                 752
Strict                   383
Flexible                 298
Super Strict 30 Days     250
Super Strict 60 Days     103
Limited                   94
Name: count, dtype: int64

In [9]:
pd.set_option('display.max_colwidth', None)
df_listings.description

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Enjoy convenient, comfortable and private accommodations in our home, located in a quiet, charming walkable neighborhood, in walking distance of NC State University and close to downtown. Perfect for NCSU visiting scholars, workshop participants, and graduation guests.  <br /><br />You will have a private entrance to the basement level of the home with your own bedroom and bathroom, and a large, comfortable den with 55" TV and other amenities.  Microwave, mini-fridge and Keurig provided.<br /><br /><b>The space</b><br />You'll have the basement all to yourself:  a simple but comfortable bedroom with full-size bed, updated private bathroom, private entrance and adjacent den with TV, DVD, and Netflix streaming but no cable. There is a mini-fridge, microwave and Keurig in the space. All linens and wifi provided. <br /><br />We're adaptable, so if you have a special request, let us know and we'll accommodate it if we can. We look forward to hosting you!<br /><br /><b>Guest access</b><br />We're well-served by public transit. A GoRaleigh bus stop just two blocks away will take you downtown or to other destinations in town. Regional GoTriangle buses with service to Chapel Hill, Durham, RTP, and RDU airport are just six blocks away. <br /><br />We have a bike available for riding to campus or downtown. There are also electric-assist bike shares and rental scooters in the neighborhood. You can get on Raleigh's wonderful greenway network in two places within about a mile of our house and ride to the renowned (and free!) NC Museum of Art, Umstead State Park, Dix Park, or Pullen Park, with its 100 year old carousel. <br /><br />On-street parking is available as well.<br /><br /><b>Other things to note</b><br />We’re open to stays longer than 4 weeks. Please message us with specifics if you’re coming to Raleigh for longer.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "The Little Nest," was named by the former owners when they completed the second story apartment above the carriage house in 1947 for a WWII veteran son and his bride.   The Airbnb is a fully equipped studio apartment in The Oakwood Historic district.  We're a short walk to all the restaurants, bars, shops, galleries, museums and other fun things in Downtown Raleigh.  Y'all come.<br /><br /><b>The space</b><br />The little nest is in a Historic Carriage house next to our home.<br /><br />It is clean, comfortable and fully equipped with lots of character.  We’re in Raleigh’s oldest neighborhood Historic Oakwood started in the 1870’s.  Its a Beautiful Historic District filled with Queen Anne, Federal, Victorian and  Craftsman homes.  We are a ten minute walk away from Downtown Raleigh, the NC State Capitol Building, the Legislature building and museums.  Its a lovely place to stroll as you make your way to and from downtown activities.<br /><br />You'll have exclusive access to the entire apartment.<br /><br />Easy access to public transportation.<br /><br /><b>Guest access</b><br />This is a private guest house which is separated from the main house and you’ll have an exclusive private entrance.<br /><br /><b>Other things to note</b><br />Eddie has a home office / Man Cave downstairs below The Little Nest.  So you may hear a tv or music.  But we have 2 important related policies:  <br />1.  We are always happy to refrain from noise tv, music or talking after 10pm on weeknights when we have guests, and <br />2. If 1. doesn't work for you, simply let us know and we'll create a personal policy for your which does :)
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Convenience - Excellent location and only 10 minutes to Raleigh's active downtown. All interstates can be easily accessed. There are many entertainment and brewery options close by. <br /><br />Space - This xtra large guest suite is in the bottom level of a split level house. You will have your own private entrance with use of a space under the carport. <br /><br />Comfort - I include amenities and comfortable furnishings for your quiet relaxation retreat.<br />Welcome to southern hospitality<br /><br /><b>The space</b><br />A 600 square foot suite in the bottom level of my house. It can accommodate 3 beds and has microwave, small fridge, coffee maker with coffee and tea service provided, use of washer and dryer, large screen smart TV with PlayStation 3, dining table with 6 chairs, and various games and movies. <br /><br />There is no kitchen availability.<br /><br /><b>Guest access</b><br />You have a private entrance from the driveway and carport. There is one step up into the suite which is one large room with bathroom.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Modern apartment in the heart of Raleigh! This property is perfect for a multi-week business-related stay, the quick pit-stop in Raleigh, and everything in between.<br /><br /><b>The space</b><br />Modern apartment in the heart of Raleigh! This property is perfect for a multi-week business-related stay, the quick pit-stop in Raleigh, and everything in between.<br /><br />This property is located in the famous Cameron village, home to Village Draft House, Café Carolina and Bakery, Cafe Caturra, Cameron Bar & Grill, Cantina 18, The Flying Biscuit Cafe, Goodberry's Creamery, Piccola Italia Pizza & Restaurant,The Village Deli and Grill, Starbucks and many more. The property is also 1 mile from all the major museums.<br /><br />Walking:The Condominium is 2 blocks away from Cameron village shops, major restaurants, markets, pharmacy, dry cleaners and a half mile from Fletcher park.<br /><br />Parking: There is plenty of free street parking in front of the property and there is one assigned parking space for the condo.<br /><br />Check In time is 3pm and Check Out time is 11am. <br /><br />Included for your stay:<br />- KING BED<br />- clean towels and linens <br />- use of washing machine and dryer <br />- Coffee maker<br />- French Press<br />- tea, coffee, sugar, powder cream <br />- assorted condiments and spices are available. <br />- A/C and heating <br />- wireless internet<br />- Roku TV<br />- dish and hand soap <br />- toilet paper and paper towels<br />- hair dryer<br />- clothes iron<br /><br /><b>Other things to note</b><br />There is an outdoor motion detection Camera by the front door. It detects motion in the outdoor front patio only.

In [10]:
df_listings.amenities

0                                                                                                                                                                                                                   Hair dryer,Body soap,Hot water,Essentials,Hangers,Bed linens,Extra pillows and blankets,Clothing storage,TV,Game console,Board games,Air conditioning,Ceiling fan,Heating,Smoke alarm,Carbon monoxide alarm,Wifi,Dedicated workspace,Microwave,Dishes and silverware,Mini fridge,Coffee maker,Private entrance,Bikes,Free parking on premises,Free street parking
1                                                                                                                                                                                                                                                                                                       Hair dryer,Hot water,Essentials,Iron,TV,Air conditioning,Heating,Smoke alarm,Carbon monoxide alarm,Wifi,Dedicated workspace,Kitchen,Refrigerator,Microwave,Cooking basics,Dishes and silverware,Stove,Oven,Coffee maker,Private entrance,Patio or balcony,Free street parking
2                                                         Hair dryer,Shampoo,Hot water,Shower gel,Washer,Dryer,Essentials,Hangers,Bed linens,Extra pillows and blankets,Iron,TV,Game console,Books and reading material,Pack ’n play/Travel crib,Children’s books and toys,Children’s dinnerware,Outlet covers,Air conditioning,Heating,Exterior security cameras on property,Smoke alarm,Carbon monoxide alarm,Fire extinguisher,First aid kit,Wifi,Dedicated workspace,Refrigerator,Microwave,Dishes and silverware,Coffee maker,Private entrance,Backyard,Free parking on premises
3                                                                                                                                                                                                                                                               Hair dryer,Shampoo,Hot water,Washer,Dryer,Essentials,Hangers,Iron,TV,Air conditioning,Heating,Exterior security cameras on property,Smoke alarm,Wifi,Kitchen,Refrigerator,Microwave,Cooking basics,Dishes and silverware,Stove,Oven,Coffee maker,Free parking on premises,Free street parking,Long term stays allowed
4                                                                                                                                                                                                           Hair dryer,Hot water,Washer,Dryer,Essentials,Bed linens,Iron,TV,Air conditioning,Heating,Smoke alarm,Carbon monoxide alarm,Fire extinguisher,Wifi,Dedicated workspace,Kitchen,Refrigerator,Microwave,Cooking basics,Dishes and silverware,Mini fridge,Hot water kettle,Coffee maker,Toaster,Dining table,Coffee,Free parking on premises,Free street parking,Pets allowed
                                                                                                                                                                                                                                                                                            ...
2877                                                                                                                                                                                             TV,Cable TV,Blender,Wifi,Air conditioning,Kitchen,Free parking on premises,Pool table,Ceiling fan,Pets allowed,Bed linens,Laundromat nearby,Hot tub,Microwave,Coffee maker,Indoor fireplace,Dishwasher,Dishes and silverware,Heating,Cooking basics,Oven,Stove,Washer,Dryer,Smoke alarm,Carbon monoxide alarm,Patio or balcony,First aid kit,Backyard,Fire extinguisher,Iron,Toaster
2878                                                                                                                                                        Pets allowed,Washer,Dryer,Essentials,Iron,TV,Air conditioning,Indoor fireplace,Ceiling fan,Heating,Smoke alarm,Carbon monoxide alarm,Fire extinguisher,First aid kit,Wifi,Kitchen,Refrigerator,Microwave,Cooking basics,Dishes and silverware,Dishwasher,Stove,Oven,Hot water kettle,Coffee maker,Toaster,Blender,Barbecue utensils,Dining table,Private entrance,Laundromat nearby,Patio or balcony,Backyard,Hot tub,Gym
2879                                                                                                                                                                                                   Hair dryer,Shampoo,Hot water,Washer,Dryer,Essentials,Hangers,Bed linens,Extra pillows and blankets,Iron,TV,Air conditioning,Indoor fireplace,Heating,Smoke alarm,Carbon monoxide alarm,Fire extinguisher,Wifi,Kitchen,Refrigerator,Microwave,Cooking basics,Dishes and silverware,Coffee maker,Private entrance,Free parking on premises,Pool,Elevator,Long term stays allowed
2880    Pets allowed,Bathtub,Hair dryer,Shampoo,Conditioner,Body soap,Hot water,Washer,Dryer,Essentials,Hangers,Bed linens,Extra pillows and blankets,Room-darkening shades,Iron,Clothing storage,TV,Air conditioning,Heating,Smoke alarm,Carbon monoxide alarm,Fire extinguisher,First aid kit,Wifi,Dedicated workspace,Kitchen,Refrigerator,Microwave,Cooking basics,Dishes and silverware,Dishwasher,Stove,Oven,Coffee maker,Baking sheet,Blender,Dining table,Coffee,Private entrance,Patio or balcony,Outdoor furniture,Free parking on premises,Pool,Elevator,Single level home
2881                                                                                                                                                  Hair dryer,Hot water,Washer,Dryer,Essentials,Bed linens,Iron,Ethernet connection,TV,Outdoor playground,Air conditioning,Indoor fireplace,Ceiling fan,Heating,Exterior security cameras on property,Smoke alarm,Carbon monoxide alarm,Fire extinguisher,Wifi,Kitchen,Refrigerator,Microwave,Cooking basics,Dishes and silverware,Oven,Coffee maker,Toaster,Private entrance,Patio or balcony,Outdoor furniture,BBQ grill,Hot tub
Name: amenities, Length: 2882, dtype: str

In [11]:
df_listings.merge(df_past, how="left", on="listing_id", indicator=True)["_merge"].value_counts()

_merge
both          34105
left_only         0
right_only        0
Name: count, dtype: int64

In [12]:
df_listings.merge(df_future, how="left", on="listing_id", indicator=True)["_merge"].value_counts()

_merge
both          33492
left_only        91
right_only        0
Name: count, dtype: int64

In [13]:
df_future.merge(df_past, how="left", on="listing_id", indicator=True)["_merge"].value_counts()

_merge
both          401616
left_only          0
right_only         0
Name: count, dtype: int64