In [1]:
import pandas as pd

import os
import sys
os.chdir("..")

df_listings = pd.read_csv('data/combined_csvs/listings_zipcode.csv')
df_future = pd.read_csv('data/combined_csvs/future_rates.csv')
df_past = pd.read_csv('data/combined_csvs/past_rates.csv')
df_reviews = pd.read_csv('data/combined_csvs/reviews.csv')

In [2]:
df_listings.columns

Index(['listing_id', 'listing_name', 'description', 'listing_type',
       'room_type', 'cover_photo_url', 'photos_count', 'photo_urls', 'host_id',
       'host_name', 'cohost_ids', 'cohost_names', 'superhost', 'latitude',
       'longitude', 'guests', 'bedrooms', 'beds', 'baths', 'registration',
       'amenities', 'instant_book', 'professional_management', 'min_nights',
       'cancellation_policy', 'checkin_time', 'checkout_time',
       'guest_favorite', 'exact_location', 'currency', 'cleaning_fee',
       'extra_guest_fee', 'single_fee_structure', 'num_reviews',
       'rating_overall', 'rating_accuracy', 'rating_checkin',
       'rating_cleanliness', 'rating_communication', 'rating_location',
       'rating_value', 'ttm_revenue', 'ttm_revenue_native', 'ttm_avg_rate',
       'ttm_avg_rate_native', 'ttm_occupancy', 'ttm_adjusted_occupancy',
       'ttm_revpar', 'ttm_revpar_native', 'ttm_adjusted_revpar',
       'ttm_adjusted_revpar_native', 'ttm_avg_min_nights',
       'ttm_avg_length_of_stay', 'ttm_reserved_days', 'ttm_blocked_days',
       'ttm_available_days', 'ttm_total_days', 'l90d_revenue',
       'l90d_revenue_native', 'l90d_avg_rate', 'l90d_avg_rate_native',
       'l90d_occupancy', 'l90d_adjusted_occupancy', 'l90d_revpar',
       'l90d_revpar_native', 'l90d_adjusted_revpar',
       'l90d_adjusted_revpar_native', 'l90d_avg_min_nights',
       'l90d_avg_length_of_stay', 'l90d_reserved_days', 'l90d_blocked_days',
       'l90d_available_days', 'l90d_total_days', 'city', 'Geocodio Latitude',
       'Geocodio Longitude', 'Geocodio Accuracy Score',
       'Geocodio Accuracy Type', 'Geocodio Address Line 1',
       'Geocodio Address Line 2', 'Geocodio Address Line 3',
       'Geocodio Address Line 4', 'Geocodio House Number', 'Geocodio Street',
       'Geocodio Unit Type', 'Geocodio Unit Number', 'Geocodio City',
       'Geocodio State / Province', 'Geocodio Nation', 'Geocodio County',
       'Geocodio Postal Code', 'Geocodio Country', 'Geocodio Building Name',
       'Geocodio Source', 'Geocodio Stable Address Key',
       'Geocodio Match Type'],
      dtype='str')

In [3]:
len(df_listings)

2882

In [4]:
df_listings['Geocodio Address Line 1'].value_counts().head(5)

Geocodio Address Line 1
1434 Upper Middle Creek Rd        23
16 Cedar Creek Ln                 22
3601 Ironbound Rd                 21
5507 N Ocean Blvd                 19
231 Greensprings Plantation Dr    14
Name: count, dtype: int64

In [5]:
df_listings['Geocodio Address Line 3'].value_counts().head(5)

Geocodio Address Line 3
Gatlinburg, TN 37738        294
Carolina Beach, NC 28428    271
Pigeon Forge, TN 37863      201
Myrtle Beach, SC 29577      197
Williamsburg, VA 23188      144
Name: count, dtype: int64

In [6]:
df_listings["zipcode"] = df_listings['Geocodio Address Line 3'].map(lambda x: int(x[-5:]))

In [7]:
df_listings["zipcode"].head()

0    27607
1    27604
2    27604
3    27605
4    27604
Name: zipcode, dtype: int64

In [8]:
zillow_dfs = []
for n_bedrooms in range(1, 6):
    file_path = f"/Users/alanchen/Documents/IAA_Summer_Practicum/data/zillow/Zip_zhvi_bdrmcnt_{n_bedrooms}_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv"
    df = pd.read_csv(file_path)
    df = df.copy()
    df["bedrooms"] = n_bedrooms
    zillow_dfs.append(df)

# Now combine them all at once
zillow_df = pd.concat(zillow_dfs, ignore_index=True)

In [9]:
zillow_df.head(1)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2000-01-31,...,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,bedrooms
0,61148,2,8701,zip,NJ,NJ,Lakewood,"New York-Newark-Jersey City, NY-NJ-PA",Ocean County,45322.82501,...,153209.294131,154016.426631,154732.546462,154927.126362,154666.047514,154048.482323,153651.615802,153199.741001,153424.560259,1

In [10]:
df_listings["bedrooms"].value_counts(dropna=False)

bedrooms
2.0     873
1.0     832
3.0     499
NaN     322
4.0     234
5.0      72
6.0      30
7.0       8
9.0       6
8.0       5
12.0      1
Name: count, dtype: int64

In [11]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
df_listings[df_listings["bedrooms"].isna() & (df_listings["room_type"] != "private_room")].head()

,listing_id,listing_name,description,listing_type,room_type,cover_photo_url,photos_count,photo_urls,host_id,host_name,cohost_ids,cohost_names,superhost,latitude,longitude,guests,bedrooms,beds,baths,registration,amenities,instant_book,professional_management,min_nights,cancellation_policy,checkin_time,checkout_time,guest_favorite,exact_location,currency,cleaning_fee,extra_guest_fee,single_fee_structure,num_reviews,rating_overall,rating_accuracy,rating_checkin,rating_cleanliness,rating_communication,rating_location,rating_value,ttm_revenue,ttm_revenue_native,ttm_avg_rate,ttm_avg_rate_native,ttm_occupancy,ttm_adjusted_occupancy,ttm_revpar,ttm_revpar_native,ttm_adjusted_revpar,ttm_adjusted_revpar_native,ttm_avg_min_nights,ttm_avg_length_of_stay,ttm_reserved_days,ttm_blocked_days,ttm_available_days,ttm_total_days,l90d_revenue,l90d_revenue_native,l90d_avg_rate,l90d_avg_rate_native,l90d_occupancy,l90d_adjusted_occupancy,l90d_revpar,l90d_revpar_native,l90d_adjusted_revpar,l90d_adjusted_revpar_native,l90d_avg_min_nights,l90d_avg_length_of_stay,l90d_reserved_days,l90d_blocked_days,l90d_available_days,l90d_total_days,city,Geocodio Latitude,Geocodio Longitude,Geocodio Accuracy Score,Geocodio Accuracy Type,Geocodio Address Line 1,Geocodio Address Line 2,Geocodio Address Line 3,Geocodio Address Line 4,Geocodio House Number,Geocodio Street,Geocodio Unit Type,Geocodio Unit Number,Geocodio City,Geocodio State / Province,Geocodio Nation,Geocodio County,Geocodio Postal Code,Geocodio Country,Geocodio Building Name,Geocodio Source,Geocodio Stable Address Key,Geocodio Match Type,zipcode
2,687864,Large space comfort and convenience!,Convenience - Excellent location and only 10 m...,Entire guest suite,entire_home,https://a0.muscache.com/im/pictures/airflow/Ho...,17.0,https://a0.muscache.com/im/pictures/airflow/Ho...,2776654,Brian,NaN,NaN,True,35.8082,-78.5734,3.0,NaN,2.0,1.0,False,"Hair dryer,Shampoo,Hot water,Shower gel,Washer...",NaN,False,1.0,Moderate,3:00 PM,11:00 AM,True,False,USD,0.0,0.0,True,853.0,4.86,4.9,5.0,4.9,4.9,4.8,4.9,22534.0,22534.0,67.8,67.8,0.912,0.912,61.7,61.7,61.7,61.7,1.0,1.8,333,0,32,365,5770.0,5770.0,74.1,74.1,0.867,0.867,64.1,64.1,64.1,64.1,1.0,1.8,78,0,12,90,raleigh,35.808225,-78.573125,1.0,rooftop,3900 Dogwood Dr,NaN,"Raleigh, NC 27604",NaN,3900,Dogwood Dr,NaN,NaN,Raleigh,NC,NaN,Wake County,27604,US,NaN,NC Geographic Information Coordinating Council,gcod_usnjfu7gz6xkpet7lflyxtrb33mld,NaN,27604
37,14179496,A modern slice of historic downtown.,"Located in the heart of historic Oakwood, our ...",Entire rental unit,entire_home,NaN,NaN,https://a0.muscache.com/im/pictures/65c66766-2...,9146297,Michael,8555157,Steve & Trish,True,35.7830,-78.6324,2.0,NaN,1.0,1.0,False,"Hair dryer,Cleaning products,Shampoo,Condition...",NaN,False,3.0,Flexible,3:00 PM,11:00 AM,True,False,USD,75.0,0.0,True,276.0,4.90,4.9,5.0,5.0,5.0,4.9,4.8,25170.0,25170.0,119.4,119.4,0.526,0.526,62.4,62.4,62.4,62.4,3.0,5.6,192,0,173,365,8064.0,8064.0,113.5,113.5,0.700,0.700,78.8,78.8,78.8,78.8,3.0,4.8,63,0,27,90,raleigh,35.783044,-78.632411,1.0,rooftop,219 North East St,NaN,"Raleigh, NC 27601",NaN,219,North East St,NaN,NaN,Raleigh,NC,NaN,Wake County,27601,US,NaN,Wake,gcod_usnxcxhv6kjknga8y6qfmdcq463gd,building_centroid,27601
96,27358914,BEST Tiny House in Raleigh - Walk to Restaurants!,Modern tiny house located in the heart of the ...,Entire guesthouse,entire_home,https://a0.muscache.com/im/pictures/hosting/Ho...,19.0,https://a0.muscache.com/im/pictures/hosting/Ho...,214920,Ellen,15378546,Darla,True,35.7946,-78.6340,2.0,NaN,1.0,1.0,False,"Hair dryer,Cleaning products,Shampoo,Hot water...",NaN,False,1.0,Flexible,3:00 PM,10:00 AM,True,False,USD,95.0,0.0,True,445.0,4.94,5.0,5.0,5.0,5.0,5.0,4.9,40451.0,40451.0,145.6,145.6,0.627,0.627,92.1,92.1,92.1,92.1,1.3,2.1,229,0,136,365,10378.0,10378.0,177.3,177.3,0.544,0.544,99.5,99.5,99.5,99.5,1.3,2.5,49,0,41,90,raleigh,35.794751,-78.633828,1.0,rooftop,204 Poplar St,NaN,"Raleigh, NC 27604",NaN,204,Poplar St,NaN,NaN,Raleigh,NC,NaN,Wake County,27604,US,NaN,Wake,gcod_usnfmrz56cklhe4cwqaef74k2tmq8,building_centroid,27604
174,41346857,Sweet Suite - Close to Downtown!,Adorable 300 sq ft private studio suite within...,Entire guest suite,entire_home,https://a0.muscache.com/im/pictures/miso/Hosti...,14.0,https://a0.muscache.com/im/pictures/miso/Hosti...,15378546,Darla,NaN,NaN,True,35.7674,-78.6247,2.0,NaN,1.0,1.0,True,"Bathtub,Hair dryer,Cleaning products,Shampoo,C...",NaN,False,1.0,Flexible,3:00 PM,10:00 AM,True,False,USD,95.0,0.0,True,537.0,4.96,5.0,5.0,5.0,5.0,4.9,4.9,36624.0,36624.0,136.5,136.5,0.600,0.600,82.1,82.1,82.1,82.1,1.3,2.4,219,0,146,365,8840.0,8840.0,151.4,151.4,0.533,0.533,82.4,82.4,82.4,82.4,1.3,2.5,48,0,42,90,raleigh,35.767576,-78.624443,1.0,rooftop,1107 S State St,NaN,"Raleigh, NC 27601",NaN,1107,S State St,NaN,NaN,Raleigh,NC,NaN,Wake County,27601,US,NaN,Wake,gcod_usn2asdnn386gncgzn27dmn6aexb6,building_centroid,27601
219,47198826,Modern Downtown Raleigh Cottage,"Great location! Comfortable, clean home. Per...",Entire cottage,entire_home,https://a0.muscache.com/im/pictures/5b1fcf58-3...,14.0,https://a0.muscache.com/im/pictures/5b1fcf58-3...,26174231,Anil,NaN,NaN,True,35.7722,-78.6314,2.0,NaN,1.0,1.0,False,"Hair dryer,Cleaning products,Shampoo,Condition...",NaN,False,2.0,Flexible,3:00 PM,11:00 AM,True,False,USD,60.0,0.0,True,405.0,4.94,5.0,5.0,4.9,4.9,4.9,4.9,28990.0,28990.0,112.5,112.5,0.603,0.603,68.6,68.6,68.6,68.6,2.0,2.9,220,0,145,365,7639.0,7639.0,122.5,122.5,0.622,0.622,74.2,74.2,74.2,74.2,2.0,3.1,56,0,34,90,raleigh,35.772249,-78.630917,1.0,rooftop,601 E South St,NaN,"Raleigh, NC 27601",NaN,601,E South St,NaN,NaN,Raleigh,NC,NaN,Wake County,27601,US,NaN,NC Geographic Information Coordinating Council,gcod_usn9fr7v6kq3mpl96plbjl284gybc,NaN,27601

In [12]:
df_listings[df_listings["bedrooms"].isna()]['room_type'].value_counts()

room_type
private_room    221
entire_home      98
shared_room       3
Name: count, dtype: int64

In [13]:
# Filter to private rooms and fill the missing values in 'bedrooms' as 1
df_listings.loc[df_listings['room_type'] == 'private_room', 'bedrooms'] = df_listings.loc[df_listings['room_type'] == 'private_room', 'bedrooms'].fillna(1)
# Filter to shared rooms and fill the missing values in 'bedrooms' as 1
df_listings.loc[df_listings['room_type'] == 'shared_room', 'bedrooms'] = df_listings.loc[df_listings['room_type'] == 'shared_room', 'bedrooms'].fillna(1)

In [14]:
# fill remaining na value for bedrooms with the median value for the corresponding number of guests 
df_listings['bedrooms'] = df_listings['bedrooms'].fillna(
    df_listings.groupby(['guests'])['bedrooms'].transform('median')
)

In [15]:
df_listings[df_listings["bedrooms"].isna()]['room_type'].value_counts()

Series([], Name: count, dtype: int64)

In [16]:
#remove extra columns from geocodio
cols_to_remove = [col for col in df_listings.columns if ("Geocodio" in col) and (col != "Geocodio Address Line 1")]
df_listings = df_listings.drop(columns=cols_to_remove)

In [17]:
df_listings[["zipcode", "bedrooms"]].head()

   zipcode  bedrooms
0    27607       1.0
1    27604       1.0
2    27604       1.0
3    27605       1.0
4    27604       1.0

In [18]:
zillow_df.rename(columns={'RegionName': 'zipcode'}, inplace=True)
zillow_df[["zipcode", "bedrooms", "2026-05-31", "SizeRank"]].head()

   zipcode  bedrooms     2026-05-31  SizeRank
0     8701         1  153424.560259         2
1    11368         1  326113.945094         4
2    77084         1  101201.674921         5
3    11385         1  610282.873960         7
4    90011         1  483999.339327        10

In [19]:
len(df_listings)

2882

In [20]:
# Match on BOTH zipcode and bedrooms to keep it a clean 1:1 row match
df_listings = df_listings.merge(
    zillow_df[["zipcode", "bedrooms", "2026-05-31", "SizeRank"]], 
    how="left", 
    on=["zipcode", "bedrooms"]
).rename(columns={"2026-05-31": "property_val"})

In [21]:
df_listings["gross_yield"] = df_listings["ttm_revenue"] / df_listings["property_val"]

In [22]:
# df_listings.to_csv('data/combined_csvs/listings_property_vals.csv', index=False)
# zillow_df.to_csv('data/zillow.csv', index=False)

In [23]:
len(df_listings)

2882

In [32]:
pd.set_option('display.max_columns', None)
df_listings[pd.isna(df_listings["gross_yield"])]["bedrooms"].value_counts()

bedrooms
1.0     143
6.0      30
5.0      18
7.0       8
9.0       6
8.0       5
12.0      1
4.0       1
Name: count, dtype: int64